services:
  sgcc_electricity_app:
    env_file:
      - .env
    image: registry.cn-hangzhou.aliyuncs.com/arcw/sgcc_electricity:latest # for use docker.io: arcw/sgcc_electricity:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: sgcc_electricity
    networks:
      1panel-network:
    environment:
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=Asia/Shanghai
    restart: unless-stopped
    volumes:
      - ./data:/data        # if you want to read homeassistant.db, homeassistant.db is in the container at /data/
      - ./scripts:/app
    command: python3 main.py 

networks:
  1panel-network:
    external: true
